var AvailableModificationsWindowComponent_8cs =
[
    [ "LDOE.UI.Windows.WorkbenchModification.Components.AvailableModificationsWindowComponent", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchModification_1_1Components_1_1AvailableModificationsWindowComponent.html", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchModification_1_1Components_1_1AvailableModificationsWindowComponent" ]
];