var BuffExpirationMeleeAutoAttackCondition_8cs =
[
    [ "LDOE.Features.Mechanics.Buffs.Base.BuffExpirationMeleeAutoAttackCondition", "classLDOE_1_1Features_1_1Mechanics_1_1Buffs_1_1Base_1_1BuffExpirationMeleeAutoAttackCondition.html", "classLDOE_1_1Features_1_1Mechanics_1_1Buffs_1_1Base_1_1BuffExpirationMeleeAutoAttackCondition" ]
];