var BuffExpirationMeleeAttackComponent_8cs =
[
    [ "LDOE.Features.Mechanics.Buffs.Components.BuffExpirationMeleeAttackComponent", "structLDOE_1_1Features_1_1Mechanics_1_1Buffs_1_1Components_1_1BuffExpirationMeleeAttackComponent.html", "structLDOE_1_1Features_1_1Mechanics_1_1Buffs_1_1Components_1_1BuffExpirationMeleeAttackComponent" ]
];