var BuildingUpgradeInfoPanelComponent_8cs =
[
    [ "LDOE.UI.Windows.Buildings.Upgrade.Components.BuildingUpgradeInfoPanelComponent", "classLDOE_1_1UI_1_1Windows_1_1Buildings_1_1Upgrade_1_1Components_1_1BuildingUpgradeInfoPanelComponent.html", "classLDOE_1_1UI_1_1Windows_1_1Buildings_1_1Upgrade_1_1Components_1_1BuildingUpgradeInfoPanelComponent" ]
];