var CharacterBuffZoneConfig_8cs =
[
    [ "LDOE.Features.Mechanics.TriggerZones.Configs.Specific.CharacterBuffZoneConfig", "classLDOE_1_1Features_1_1Mechanics_1_1TriggerZones_1_1Configs_1_1Specific_1_1CharacterBuffZoneConfig.html", "classLDOE_1_1Features_1_1Mechanics_1_1TriggerZones_1_1Configs_1_1Specific_1_1CharacterBuffZoneConfig" ]
];