var DescriptionPanelComponentBase_8cs =
[
    [ "LDOE.UI.Windows.Components.DescriptionPanels.DescriptionPanelComponentBase", "classLDOE_1_1UI_1_1Windows_1_1Components_1_1DescriptionPanels_1_1DescriptionPanelComponentBase.html", "classLDOE_1_1UI_1_1Windows_1_1Components_1_1DescriptionPanels_1_1DescriptionPanelComponentBase" ]
];