var IAuthenticationServerServicesProvider_8cs =
[
    [ "LDOE.Network.ServerConnection.Authentication.IAuthenticationServerServicesProvider", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Authentication_1_1IAuthenticationServerServicesProvider.html", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Authentication_1_1IAuthenticationServerServicesProvider" ]
];