var IAuthenticationServerConnectionHandler_8cs =
[
    [ "LDOE.Network.ServerConnection.Authentication.IAuthenticationServerConnectionHandler", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Authentication_1_1IAuthenticationServerConnectionHandler.html", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Authentication_1_1IAuthenticationServerConnectionHandler" ]
];