var ICommunicationServerServicesProvider_8cs =
[
    [ "LDOE.Network.ServerConnection.Communication.ICommunicationServerServicesProvider", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Communication_1_1ICommunicationServerServicesProvider.html", "interfaceLDOE_1_1Network_1_1ServerConnection_1_1Communication_1_1ICommunicationServerServicesProvider" ]
];