var IHighlightRestriction_8cs =
[
    [ "LDOE.UI.Tutorial.Scripts.Actions.HighlightRestrictions.IHighlightRestriction", "interfaceLDOE_1_1UI_1_1Tutorial_1_1Scripts_1_1Actions_1_1HighlightRestrictions_1_1IHighlightRestriction.html", "interfaceLDOE_1_1UI_1_1Tutorial_1_1Scripts_1_1Actions_1_1HighlightRestrictions_1_1IHighlightRestriction" ]
];