var ISceneEntityInitializer_8cs =
[
    [ "LDOE.Features.Mechanics.GameScene.SceneComponents.Initializers.ISceneEntityInitializerLogicTick", "interfaceLDOE_1_1Features_1_1Mechanics_1_1GameScene_1_1SceneComponents_1_1Initializers_1_1ISceneEntityInitializerLogicTick.html", "interfaceLDOE_1_1Features_1_1Mechanics_1_1GameScene_1_1SceneComponents_1_1Initializers_1_1ISceneEntityInitializerLogicTick" ],
    [ "LDOE.Features.Mechanics.GameScene.SceneComponents.Initializers.ISceneEntityInitializerNoLogic", "interfaceLDOE_1_1Features_1_1Mechanics_1_1GameScene_1_1SceneComponents_1_1Initializers_1_1ISceneEntityInitializerNoLogic.html", "interfaceLDOE_1_1Features_1_1Mechanics_1_1GameScene_1_1SceneComponents_1_1Initializers_1_1ISceneEntityInitializerNoLogic" ]
];