var ItemUpgradeWorldEvent_8cs =
[
    [ "LDOE.Features.Mechanics.Items.Features.Upgrade.WorldEvents.ItemUpgradeWorldEvent", "structLDOE_1_1Features_1_1Mechanics_1_1Items_1_1Features_1_1Upgrade_1_1WorldEvents_1_1ItemUpgradeWorldEvent.html", "structLDOE_1_1Features_1_1Mechanics_1_1Items_1_1Features_1_1Upgrade_1_1WorldEvents_1_1ItemUpgradeWorldEvent" ],
    [ "LDOE.Features.Mechanics.Items.Features.Upgrade.WorldEvents.ItemUpgradeWorldEventHandler", "classLDOE_1_1Features_1_1Mechanics_1_1Items_1_1Features_1_1Upgrade_1_1WorldEvents_1_1ItemUpgradeWorldEventHandler.html", "classLDOE_1_1Features_1_1Mechanics_1_1Items_1_1Features_1_1Upgrade_1_1WorldEvents_1_1ItemUpgradeWorldEventHandler" ]
];