var ItemPanelComponentBase_8cs =
[
    [ "LDOE.UI.Windows.WorkbenchGunsmith.Components.ItemPanels.ItemPanelComponentBase", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchGunsmith_1_1Components_1_1ItemPanels_1_1ItemPanelComponentBase.html", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchGunsmith_1_1Components_1_1ItemPanels_1_1ItemPanelComponentBase" ]
];