var LocalOfferEntryCurrencyModel_8cs =
[
    [ "LDOE.Network.ServerConnection.Main.Offline.Services.Configs.LocalOfferEntryCurrencyModel", "classLDOE_1_1Network_1_1ServerConnection_1_1Main_1_1Offline_1_1Services_1_1Configs_1_1LocalOfferEntryCurrencyModel.html", "classLDOE_1_1Network_1_1ServerConnection_1_1Main_1_1Offline_1_1Services_1_1Configs_1_1LocalOfferEntryCurrencyModel" ]
];