var ModificationInventoryPanelComponent_8cs =
[
    [ "LDOE.UI.Windows.WorkbenchModification.Components.ModificationInventoryPanelComponent", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchModification_1_1Components_1_1ModificationInventoryPanelComponent.html", "classLDOE_1_1UI_1_1Windows_1_1WorkbenchModification_1_1Components_1_1ModificationInventoryPanelComponent" ]
];