var namespaceLDOE_1_1Features_1_1Mechanics_1_1LocationTasks_1_1Serializers =
[
    [ "LocationTaskConditionSerializer", "classLDOE_1_1Features_1_1Mechanics_1_1LocationTasks_1_1Serializers_1_1LocationTaskConditionSerializer.html", "classLDOE_1_1Features_1_1Mechanics_1_1LocationTasks_1_1Serializers_1_1LocationTaskConditionSerializer" ],
    [ "LocationTaskSerializer", "classLDOE_1_1Features_1_1Mechanics_1_1LocationTasks_1_1Serializers_1_1LocationTaskSerializer.html", "classLDOE_1_1Features_1_1Mechanics_1_1LocationTasks_1_1Serializers_1_1LocationTaskSerializer" ]
];