var OfflineGlobalBossesService_8cs =
[
    [ "LDOE.Network.ServerConnection.Room.Offline.Services.OfflineGlobalBossesService", "classLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflineGlobalBossesService.html", "classLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflineGlobalBossesService" ]
];