var OfflinePublicRoomService_8cs =
[
    [ "LDOE.Network.ServerConnection.Room.Offline.Services.OfflinePublicRoomService", "classLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflinePublicRoomService.html", "classLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflinePublicRoomService" ],
    [ "LDOE.Network.ServerConnection.Room.Offline.Services.OfflinePublicRoomService.RoomParameters", "structLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflinePublicRoomService_1_1RoomParameters.html", "structLDOE_1_1Network_1_1ServerConnection_1_1Room_1_1Offline_1_1Services_1_1OfflinePublicRoomService_1_1RoomParameters" ]
];