var OverviewDescriptionPanelComponent_8cs =
[
    [ "LDOE.UI.Windows.Components.DescriptionPanels.OverviewDescriptionPanelComponent", "classLDOE_1_1UI_1_1Windows_1_1Components_1_1DescriptionPanels_1_1OverviewDescriptionPanelComponent.html", "classLDOE_1_1UI_1_1Windows_1_1Components_1_1DescriptionPanels_1_1OverviewDescriptionPanelComponent" ]
];