var SetBuildingHealthWorldEvent_8cs =
[
    [ "LDOE.Features.Mechanics.Building.WorldEvents.SetBuildingHealthWorldEvent", "structLDOE_1_1Features_1_1Mechanics_1_1Building_1_1WorldEvents_1_1SetBuildingHealthWorldEvent.html", "structLDOE_1_1Features_1_1Mechanics_1_1Building_1_1WorldEvents_1_1SetBuildingHealthWorldEvent" ],
    [ "LDOE.Features.Mechanics.Building.WorldEvents.SetBuildingHealthWorldEventHandler", "classLDOE_1_1Features_1_1Mechanics_1_1Building_1_1WorldEvents_1_1SetBuildingHealthWorldEventHandler.html", "classLDOE_1_1Features_1_1Mechanics_1_1Building_1_1WorldEvents_1_1SetBuildingHealthWorldEventHandler" ]
];