var WorkbenchTaskProcessComponent_8cs =
[
    [ "LDOE.Features.Mechanics.Workbenches.Components.WorkbenchTaskProcessComponent", "structLDOE_1_1Features_1_1Mechanics_1_1Workbenches_1_1Components_1_1WorkbenchTaskProcessComponent.html", "structLDOE_1_1Features_1_1Mechanics_1_1Workbenches_1_1Components_1_1WorkbenchTaskProcessComponent" ]
];